Give more meaningful error messages on empty backtest.
Currently pyfolio throws an error with an empty backtest (i.e. backtest that have no position)

Previously on backtest failure we will be greeted with a meesage:
```
pyfolio/pos.pyc in extract_pos(positions, cash)

AttributeError: 'DataFrame' object has no attribute 'amount'
```
This is just a change to make the error message more obvious.